# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "Unit Tests"
  inputs:
    command: 'test'
    projects: '**/Temperature.Converter.Tests'

- task: DotNetCoreCLI@2
  displayName: "Publish"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-o $(build.artifactstagingdirectory)/out'
    zipAfterPublish: false
    modifyOutputPath: false

- task: Docker@2
  inputs:
    containerRegistry: 'marcelgol.acr.io'
    repository: 'temperatureconverter'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(build.artifactstagingdirectory)'